---
# requires the mini-lab to be running
- name: Running modules
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    metal_stack_release_version: v0.1.0
    metal_api_url: http://api.0.0.0.0.xip.io:8080/metal
    metal_api_hmac: metal-admin
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - ansible-common
    - metal-roles
  tasks:
    - name: Gather releases
      setup_yaml:

    - name: Install metal-python
      pip:
        #name: git+https://github.com/metal-stack/metal-python@spec-corrections
        name: metal_python
        version: "{{ metal_metalctl_image_tag }}"

    - name: Allocate network
      metal_network:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        name: test
        partition: vagrant
        project: 00000000-0000-0000-0000-000000000000
      register: network

    - name: Allocate IP
      metal_ip:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        network: "{{ network.id }}"
        project: 00000000-0000-0000-0000-000000000000
      register: ip

    - name: Release IP
      metal_ip:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        ip: "{{ ip.ip }}"
        state: absent

    - name: Release network
      metal_network:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        id: "{{ network.id }}"
        state: absent
