---
# requires the mini-lab to be running
- name: Running modules
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    metal_stack_release_version: develop
    metal_api_url: http://api.0.0.0.0.nip.io:8080/metal
    metal_api_hmac: metal-admin
    setup_yaml:
      - url: https://raw.githubusercontent.com/metal-stack/releases/{{ metal_stack_release_version }}/release.yaml
        meta_var: metal_stack_release
  roles:
    - ansible-common
    - metal-roles
    - metal-roles/control-plane/roles/metal-python
  tasks:
    - name: Allocate network
      metal_network:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        name: test
        description: test network
        partition: vagrant
        project: 00000000-0000-0000-0000-000000000000
      register: network

    - name: Lookup project network
      set_fact:
        project_networks: "{{ lookup('metal', 'search', 'network', projectid='00000000-0000-0000-0000-000000000000') }}"

    - name: Assert network
      assert:
        fail_msg: "network was not created properly"
        quiet: yes
        that:
          - project_networks | length == 1
          - project_networks[0].name == "test"
          - project_networks[0].description == "test network"
          - project_networks[0].partitionid == "vagrant"
          - project_networks[0].parentnetworkid == "tenant-super-network-vagrant"
          - project_networks[0].projectid == "00000000-0000-0000-0000-000000000000"
          - project_networks[0].nat == False
          - project_networks[0].underlay == False
          - project_networks[0].privatesuper == False
          - project_networks[0].vrf > 0

    - name: Allocate IP
      metal_ip:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        network: "{{ network.id }}"
        name: test
        description: test ip
        project: 00000000-0000-0000-0000-000000000000
      register: ip

    - name: Lookup IP
      set_fact:
        looked_up_ip: "{{ lookup('metal', 'get', 'ip', id=ip.ip) }}"

    - name: Assert IP
      assert:
        fail_msg: "ip was not created properly"
        quiet: yes
        that:
          - looked_up_ip.name == "test"
          - looked_up_ip.description == "test ip"
          - looked_up_ip.ipaddress == ip.ip
          - looked_up_ip.networkid == network.id
          - looked_up_ip.projectid == "00000000-0000-0000-0000-000000000000"
          - looked_up_ip.type == "ephemeral"

    - name: Release IP
      metal_ip:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        ip: "{{ ip.ip }}"
        state: absent

    - name: Release network
      metal_network:
        api_url: "{{ metal_api_url }}"
        api_hmac: "{{ metal_api_hmac }}"
        id: "{{ network.id }}"
        state: absent
